export const TODO_ADD = "TODO_ADD";
export const TODO_TOGGLE = "TODO_TOGGLE";
export const FILTER_SET = "FILTER_SET";
export const ASSIGNED_TO_CHANGE = "ASSIGNED_TO_CHANGE";
export const NOTIFICATION_HIDE = "NOTIFICATION_HIDE";
export const TODO_ADD_WITH_NOTIFICATION = 'TODO_ADD_WITH_NOTIFICATION';
